### ISSUE TITLE
HELP-426 Problem using 'OBI:0001985' in assay type and analysis type

### ISSUE THREAD

**Issue by jeremywalter** [nih-cfde/helpdesk-collaboration#5]
During the last submission another problem surfaced when running the submission prep and frictionless tool:

Term 'OBI:0001985' has no name: if the term ID isn't a typo, please check integrity of 'assay_type' reference file(s).

Term 'OBI:0001985' has no name: if the term ID isn't a typo, please check integrity of 'analysis_type' reference file(s).

We submitted new data files based on glycan microarray assays. OBI does not have this term but a parent term (microarray assay: OBI:0001985). When adding this term to the “assay_type” column of files.tsv the first error above showed up (during the prep and submission). I also tried to use it for “analysis_type” but a similar error appeared. Overall, I am not sure about the difference between assay and analysis in this context anyway.

Can you please:
1.	Clarify the difference between assay and analysis in this context
2.	Let us know why 'OBI:0001985' was not accepted during the submission.

**Comment by jonathancrabtree** [comment]
Hi @ReneRanzinger, I've downloaded the tsv files you provided above and am looking into this. Thanks!

**Comment by ReneRanzinger** [comment]
This is related to https://github.com/glygener/glygen.cfde.generator/issues/22.

**Comment by jeet-vora** [comment]
This issue seems to have gone with the new update of files on osf and the prep script. The issue can be closed.

**Comment by RLC-DCPPC** [comment]
Based on Jeet's comment we are closing this issue.
