### ISSUE TITLE
HELP-173 Bug report: Submission prep tool for GlyTouCan IDs

### ISSUE THREAD

**Issue by jeremywalter** [nih-cfde/helpdesk-collaboration#6]
HI,

we are submitting glycans (compounds) to CFDE. The agreement in the discussion with Arthur and Amanda was that we would provide PubChem IDs for glycans as possible and otherwise would be able to submit them as GlyTouCan IDs. However, the current submission prep tool (released Monday) does not let (certain?) GlyTouCan IDs pass. The program stops with:

FATAL: Term 'G00948WV' has no name: aborting, please check integrity of 'compound' reference file(s).

Other IDs that do not pass are G00222MO , G00786XQ.

**Comment by jonathancrabtree** [comment]
Hi @ReneRanzinger, this is another case that Arthur's notes say was closed a while back and the comments that I see from you and Jeet (above) seem to confirm this.

**Comment by ReneRanzinger** [comment]
This is related to https://github.com/glygener/glygen.cfde.generator/issues/14

**Comment by RLC-DCPPC** [comment]
Based on comments above we believe this has been addressed. We will update the CV list in sync with the next submission (mid-March 2023). Please let us know when would be a good time to do the update.
