### ISSUE TITLE
HELP-217 Missing Ensembl IDs

### ISSUE THREAD

**Issue by jeremywalter** [nih-cfde/helpdesk-collaboration#7]
When running the prep-script it works fine with a protein having the ensemble ID "ENSG00000214826". However when running the submission tool it will fail. This ID is also not present in the ensemble TSV in the reference CV folder. There are probably other IDs as but the submission stopped after the first error.

Best,
René

**Comment by jonathancrabtree** [comment]
Hi @ReneRanzinger, the notes I have from Arthur indicate that this case was closed (in June, I'm assuming) and your notes above seem to confirm this (with the exception of the protein id problem, which I'm guessing was filed as the separate case HELP-357, aka issue #1 in this repository). Can this case be closed and, if not, which Ensembl ids are causing submission problems?

**Comment by ReneRanzinger** [comment]
This is related to https://github.com/glygener/glygen.cfde.generator/issues/21 and https://github.com/glygener/glygen.cfde.generator/issues/17.
